### ISSUE TITLE
BAV Manifests

### ISSUE THREAD

**Issue by E-11-V** [TomDeneire/pictor#30]
Hi,

is Pictor suppose to allow discovery of manifests from the Vatican Library? Because the readme file says so but I have tried searching bits of text from the manifests in there and got 0 results.

**Comment by TomDeneire** [comment]
Hi,

Pictor has indexed a sample of manuscripts from the Vaticana. You can see which here: 

https://github.com/TomDeneire/pictor/blob/main/data/samples/vaticana_sample.txt

Unfortunately, Pictor can only index general labels (not each label of each canvas), so it ends up indexing only the manuscript number (which is the only data in the Vaticana labels).

It also removes numbers (perhaps it shouldn't): so `Vat.lat.333` is turned into ` vatlat` .

If you type in ` vatlat` in Pictor, you find the whole list.

This is far from ideal, but I'm afraid it's the kind of thing that happens when aggregating big data sets...

**Comment by E-11-V** [comment]
Oh, thank you for your answer and sorry! I was convinced that IIIF manifests contained a short description of the ms., which in turn allowed it to be discovered through Pictor. I see that most digitised Vatican mss have no description and hence there's nothing to be found in the manifest by Pictor but at the same time some of them (https://digi.vatlib.it/view/MSS_Arch.Cap.S.Pietro.A.30) do contain a mention of the title in the manifesto (https://digi.vatlib.it/iiif/MSS_Arch.Cap.S.Pietro.A.30/manifest.json). 

At this point I have two questions, if I may: 

1. do you expect Pictor to expand its sample of manifests at some point?
2. should the BAV add description to the mss., would that be reflected in the manifest (and therefore in Pictor)? I realise it's rather a question for them, but I'm just curious. 

Thank you for your work!

**Comment by TomDeneire** [comment]
Hi,

I think that even in the manifest you cite (https://digi.vatlib.it/iiif/MSS_Arch.Cap.S.Pietro.A.30/manifest.json) , Pictor will only index the first label registered with the manifest. So it would still miss the title, unfortunately.

The system is far from perfect, but these decisions were made to be able to index as many manifests as possible. This also means that **with the current setup** I'm afraid Pictor will not be able to expand its sample size (nor the amount of metadata it indexes). If it were ever to be upgraded to a client-server application, a lot more data could be handled.

As far as adding description to the manifests, that's up to BAV indeed. Remember, IIIF is an image protocol, so descriptive metadata is not the main focus. Still, I do think that including more than just a mere shelfmark is a good idea. Or at least a permalink to another URL where the detailed metadata can be found.

All the best!
